apiVersion: v1
kind: Pod
metadata:
  name: roadside-server
spec:
  restartPolicy: on-failure
  containers:
    - name: xtdb
      image: ghcr.io/xtdb/xtdb:2.1.0
      volumeMounts:
        - mountPath: /var/lib/xtdb
          name: xtdb-data
    - name: api
      image: localhost/roadside-server:latest
      ports:
        - containerPort: 8000
          hostIp: 127.0.0.1
          hostPort: 8000
      env:
        - name: port
          value: 8000
        - name: dbhost
          value: xtdb
  volumes:
    - name: xtdb-data
      persistentVolumeClaim:
        claimName: roadside-xtdb-data
